name: budget
description: "A new Flutter project."
publish_to: 'none'

version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  date_field: ^6.0.3+1
  intl: ^0.20.2
  flutter_localizations:
      sdk: flutter
  format: ^1.6.0
  url_launcher: ^6.1.7
  timezone: ^0.10.1
  local_auth: ^2.3.0
  pinput: ^5.0.1
  file_picker: ^10.3.1
  permission_handler: ^11.0.0
  pdf: ^3.10.1
  image: ^4.3.0
  printing: ^5.10.0
  another_flushbar: ^1.10.24
  file_saver: ^0.2.9
  excel: ^4.0.2
  open_filex: ^4.7.0
  shared_preferences: ^2.5.3
  dropdown_button2: ^2.3.9
  pie_chart: ^5.4.0
  fl_chart: ^1.1.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
    android: "launch_icon"
    ios: true
    image_path: "assets/img/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
